### PR TITLE
Prettifying Debian packaging

### PR DESCRIPTION
**Pull request by jollyroger**
Hi!

Thank you for making a Debian package and patches out of the original work. I have done a bit cleaning to make the package more compatible with Debian policy. Notable changes are:
- fixed typos
- add manpage to the binary package
- add config to the git-buildpackage (gbp) to simplify building packages
- add more files to gitignore

### CODE REVIEW

**Comment by jollyroger** [comment]
Bump.

**Comment by ralt** [comment]
Hi!

Sorry for missing this, and thanks a lot for this PR!

Just a detail: could you retain the information that this is a fork, somewhere in the description or in one of the package's metadata?

**Comment by jollyroger** [comment]
Hi! I wrote additional paragraph in the package description. Please check.

**Comment by ralt** [comment]
Thanks! I'll try to merge as soon as I get on a laptop. (Probably Monday.)

**Comment by jollyroger** [comment]
Hi again. I have rebased the Debian-related work (yours and mine) over current state of the AndriiGrytsenko/openssh-ldap-publickey repository to have SSL/TLS support. Nothing has changed apart from that.

Also I want to include this software in Debian and maintain it. I'd like to use your work as a starting point (and will state this in copyrights) if you have no objections.

**Comment by ralt** [comment]
Wooo, I totally forgot about this PR, really sorry about that. I can't take care of it right now, but am setting myself a reminder to do so this week. Sorry for the long wait.

PS: I noticed that GitHub is noticing a conflict, I guess it's because upstream merged our TLS changes?

**Comment by jollyroger** [comment]
@ralt I rebased all Debian-related changes on top of the AndriiGrytsenko/openssh-ldap-publickey in case you would like to send PR to that repository. This caused a merge conflict. I like to use `git-buildpackage` aka gbp to prepare the binary packages. For this it is better to have a separate branch with Debian-related changes and that was the reason for me to rebase your commits as well. This is a common approach to maintain packages in Debian as well. To resolve the conflict I want to propose this approach:

On your side: 
* create a separate `debian` branch from master to have all your changes, 
* revert `master` branch to a state identical to AndriiGrytsenko/openssh-ldap-publickey master branch, force-push it and then 
* rebase your `debian` branch on top of your `master`branch` 

This way you'll get debian-related stuff separated from upstream repository. Afterwards I'll update my merge request to push to your `debian` branch. When done, you should be able to easily build Debian packages with gbp. Moreover I could clone your repo with no changes to salsa.debian.org and prepare the packages for inclusion into Debian archive with no extra efforts needed.

**Comment by OriPekelman** [comment]
@jollyroger you are more than invited to take-over. We have no objections. A copyright notice is always pleasant. 

The conflicts are very minor (but not being of sufficient debian powers myself, I don't want to merge them). 

So either you can merge those yourself or we could have someone look at it towards the end of the week. Florian is off today.

**Comment by ralt** [comment]
@jollyroger would you be on an IRC server or somewhere where we can chat about this?

**Comment by jollyroger** [comment]
@ralt sure, I'm using this nick on freenode and OFTC servers and currently online.

**Comment by ralt** [comment]
As discussed on IRC:

- I'm closing this PR.
- You may use the code in this repository as you see fit to include it in the Debian Archive.
- You may add a copyright notice to `Platform.sh <sayhello@platform.sh>` for this package up to 2018.

Hoping to see this package in Debian Archive soon to make it useful for other people :)

Cheers!

**Comment by jollyroger** [comment]
Thank you!

**Pull request closed without merging**
